parameters:
#    vanessa_api.example.class: Vanessa\ApiBundle\Example

services:
#    vanessa_api.example:
#        class: %vanessa_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
