<?php

namespace Vanessa\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessageTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageTypeRepository extends EntityRepository
{

    /**
     * Get type
     *
     * @param string $type
     * @return type
     */
    public function getType($type)
    {
        $qb = $this->createQueryBuilder('m')
            ->where('m.type = :type')
            ->setParameter('type', $type);

        return $qb->getQuery()->getSingleResult();
    }

}
