<?php

namespace Vanessa\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessagesRepository extends EntityRepository
{

    /**
     * Get all artist query
     *
     * @return type
     */
    public function getAllMemberMessages($options)
    {
        $qb = $this->createQueryBuilder('m')
            ->select('m')
            ->where('m.recipient = :member')
            ->andWhere('m.isRead = 0')
            ->setParameter('member', $options['user']);
        return  $qb->getQuery()->execute();        
    }

}
