<?php

namespace Vanessa\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusRepository extends EntityRepository
{

    /**
     * Get status
     *
     * @param string $status
     * @return type
     */
    public function getStatus($status)
    {
        $objQueuryBuilder = $this->createQueryBuilder('s')
            ->where('s.name = :status_name')
            ->setParameter('status_name', $status);

        return $objQueuryBuilder->getQuery()->getSingleResult();
    }

}
