vanessa_api:
    resource: "@VanessaApiBundle/Resources/config/routing.yml"
    prefix:   /

vanessa_code:
    resource: "@VanessaCodeBundle/Resources/config/routing.yml"
    prefix:   /

vanessa_song:
    resource: "@VanessaSongBundle/Resources/config/routing.yml"
    prefix:   /

vanessa_artist:
    resource: "@VanessaArtistBundle/Resources/config/routing.yml"
    prefix:   /

vanessa_agency:
    resource: "@VanessaAgencyBundle/Resources/config/routing.yml"
    prefix:   /

vanessa_member:
    resource: "@VanessaMemberBundle/Resources/config/routing.yml"
    prefix:   /

vanessa_core:
    resource: "@VanessaCoreBundle/Resources/config/routing.yml"
    prefix:   /

_welcome:
    pattern:  /
    defaults: { _controller: VanessaCoreBundle:Site:index }
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"    