vanessa_core_site_about:
    pattern:  /aboutUs.{_format}
    defaults: { _controller: VanessaCoreBundle:Site:about , maxAge: 86400 , sharedMaxAge: 86400 , private: false , _format: html}    
    requirements:
        _method:  GET 
        _format:  html
        
vanessa_core_site_contact:
    pattern:  /contactUs.{_format}
    defaults: { _controller: VanessaCoreBundle:Site:contact , maxAge: 86400 , sharedMaxAge: 86400 , private: false , _format: html}     
    requirements:
        _method:  GET 
        _format:  html
    
vanessa_core_site_info_roles: 
    pattern:  /info/roles.{_format}
    defaults: { _controller: VanessaCoreBundle:Info:roles , maxAge: 86400 , sharedMaxAge: 86400 , private: false , _format: html}     
    requirements:
        _method:  GET 
        _format:  html  
        
vanessa_alert_get_messages:
    pattern:  /alert/get/messages.{_format}
    defaults: { _controller: VanessaCoreBundle:Alert:getMessages , _format: html}     
    requirements:
        _method:  GET 
        _format:  html  
    options:
        expose: true