vanessa_artist_list:
    pattern:  /artist/list.{_format}
    defaults: { _controller: VanessaArtistBundle:Artist:list , _format: html}        
    requirements:
        _method: GET 
        _format: html
        
vanessa_artist_new:
    pattern:  /artist/new.{_format}
    defaults: { _controller: VanessaArtistBundle:Artist:new , _format: html}        
    requirements:
        _method: GET 
        _format: html        

vanessa_artist_create:
    pattern:  /artist/create.{_format}
    defaults: { _controller: VanessaArtistBundle:Artist:create , _format: html}        
    requirements:
        _method: GET|POST 
        _format: html  

vanessa_artist_edit:
    pattern:  /artist/edit/{slug}.{_format}
    defaults: { _controller: VanessaArtistBundle:Artist:edit , _format: html}        
    requirements:
        _method: GET
        _format: html  

vanessa_artist_update:
    pattern:  /artist/update/{slug}.{_format}
    defaults: { _controller: VanessaArtistBundle:Artist:update , _format: html}        
    requirements:
        _method: GET|POST
        _format: html
        
vanessa_artist_delete:
    pattern:  /artist/delete/{slug}.{_format}
    defaults: { _controller: VanessaArtistBundle:Artist:delete , _format: html}        
    requirements:
        _method: GET|POST
        _format: html
        
vanessa_artist_profile:
    pattern:  /artist/profile/{slug}.{_format}
    defaults: { _controller: VanessaArtistBundle:Artist:profile , _format: html}        
    requirements:
        _method: GET
        _format: html          
        
vanessa_artist_account_status_show:
    pattern:  /artist/account/status/show/{slug}.{_format}
    defaults: { _controller: VanessaArtistBundle:Artist:accountStatusShow , _format: html}        
    requirements:
        _method: GET|POST
        _format: html 
        
vanessa_artist_account_status_edit:
    pattern:  /artist/account/status/edit/{slug}.{_format}
    defaults: { _controller: VanessaArtistBundle:Artist:accountStatusEdit , _format: html}        
    requirements:
        _method: GET|POST
        _format: html          

vanessa_artist_list_download_excel:
    pattern:  /artist/download/excel/list.{_format}
    defaults: { _controller: VanessaArtistBundle:Artist:downloadExcel , _format: html}        
    requirements:
        _method: GET 
        _format: html 