vanessa_agency_content_owner_list:
    pattern:  /content/owner/list.{_format}
    defaults: { _controller: VanessaAgencyBundle:ContentOwner:list , _format: html}        
    requirements:
        _method: GET 
        _format: html
        
vanessa_agency_content_owner_list_members:
    pattern:  /content/owner/members/{slug}.{_format}
    defaults: { _controller: VanessaAgencyBundle:ContentOwner:listMembers , _format: html}        
    requirements:
        _method: GET 
        _format: html
        
vanessa_agency_content_owner_list_artists:
    pattern:  /content/owner/artists/{slug}.{_format}
    defaults: { _controller: VanessaAgencyBundle:ContentOwner:listArtists , _format: html}        
    requirements:
        _method: GET 
        _format: html
        
vanessa_agency_content_owner_new:
    pattern:  /content/owner/new.{_format}
    defaults: { _controller: VanessaAgencyBundle:ContentOwner:new , _format: html}        
    requirements:
        _method: GET 
        _format: html        

vanessa_agency_content_owner_create:
    pattern:  /content/owner/create.{_format}
    defaults: { _controller: VanessaAgencyBundle:ContentOwner:create , _format: html}        
    requirements:
        _method: GET|POST 
        _format: html  

vanessa_agency_content_owner_edit:
    pattern:  /content/owner/edit/{slug}.{_format}
    defaults: { _controller: VanessaAgencyBundle:ContentOwner:edit , _format: html}        
    requirements:
        _method: GET
        _format: html  

vanessa_agency_content_owner_update:
    pattern:  /content/owner/update/{slug}.{_format}
    defaults: { _controller: VanessaAgencyBundle:ContentOwner:update , _format: html}        
    requirements:
        _method: GET|POST
        _format: html  

vanessa_agency_content_owner_profile:
    pattern:  /content/owner/profile/{slug}.{_format}
    defaults: { _controller: VanessaAgencyBundle:ContentOwner:profile , _format: html}        
    requirements:
        _method: GET
        _format: html  
        
vanessa_agency_content_owner_delete:
    pattern:  /content/owner/delete/{slug}.{_format}
    defaults: { _controller: VanessaAgencyBundle:ContentOwner:delete , _format: html}        
    requirements:
        _method: GET
        _format: html  
        
vanessa_agency_content_owner_account_status_show:
    pattern:  /content/owner/account/status/show/{slug}.{_format}
    defaults: { _controller: VanessaAgencyBundle:ContentOwner:accountStatus , _format: html}        
    requirements:
        _method: GET
        _format: html  
        
vanessa_agency_content_owner_account_status_edit:
    pattern:  /content/owner/account/status/edit/{slug}.{_format}
    defaults: { _controller: VanessaAgencyBundle:ContentOwner:accountStatusEdit , _format: html}        
    requirements:
        _method: GET|POST
        _format: html 
        
vanessa_agency_content_owner_list_download_excel:
    pattern:  /content/owner/download/excel/list.{_format}
    defaults: { _controller: VanessaAgencyBundle:ContentOwner:downloadExcel , _format: html}        
    requirements:
        _method: GET 
        _format: html 
        
vanessa_agency_content_owner_list_download_artists_excel:
    pattern:  /content/owner/download/excel/artist/list/{slug}.{_format}
    defaults: { _controller: VanessaAgencyBundle:ContentOwner:downloadArtistsExcel , _format: html}        
    requirements:
        _method: GET 
        _format: html 
        
vanessa_agency_content_owner_list_download_members_excel:
    pattern:  /content/owner/download/excel/member/list/{slug}.{_format}
    defaults: { _controller: VanessaAgencyBundle:ContentOwner:downloadMembersExcel , _format: html}        
    requirements:
        _method: GET 
        _format: html 
        
        
vanessa_agency_reseller_list:
    pattern:  /reseller/list.{_format}
    defaults: { _controller: VanessaAgencyBundle:Reseller:list , _format: html}        
    requirements:
        _method: GET 
        _format: html  
        
vanessa_agency_reseller_list_members:
    pattern:  /reseller/members/{slug}.{_format}
    defaults: { _controller: VanessaAgencyBundle:Reseller:listMembers , _format: html}        
    requirements:
        _method: GET 
        _format: html        
        
vanessa_agency_reseller_new:
    pattern:  /reseller/new.{_format}
    defaults: { _controller: VanessaAgencyBundle:Reseller:new , _format: html}        
    requirements:
        _method: GET 
        _format: html        

vanessa_agency_reseller_create:
    pattern:  /reseller/create.{_format}
    defaults: { _controller: VanessaAgencyBundle:Reseller:create , _format: html}        
    requirements:
        _method: GET|POST 
        _format: html  

vanessa_agency_reseller_edit:
    pattern:  /reseller/edit/{slug}.{_format}
    defaults: { _controller: VanessaAgencyBundle:Reseller:edit , _format: html}        
    requirements:
        _method: GET
        _format: html  

vanessa_agency_reseller_update:
    pattern:  /reseller/update/{slug}.{_format}
    defaults: { _controller: VanessaAgencyBundle:Reseller:update , _format: html}        
    requirements:
        _method: GET|POST
        _format: html  

vanessa_agency_reseller_profile:
    pattern:  /reseller/profile/{slug}.{_format}
    defaults: { _controller: VanessaAgencyBundle:Reseller:profile , _format: html}        
    requirements:
        _method: GET
        _format: html  
        
vanessa_agency_reseller_delete:
    pattern:  /reseller/delete/{slug}.{_format}
    defaults: { _controller: VanessaAgencyBundle:Reseller:delete , _format: html}        
    requirements:
        _method: GET
        _format: html  
        
vanessa_agency_reseller_account_status_show:
    pattern:  /reseller/account/status/show/{slug}.{_format}
    defaults: { _controller: VanessaAgencyBundle:Reseller:accountStatus , _format: html}        
    requirements:
        _method: GET
        _format: html  
        
vanessa_agency_reseller_account_status_edit:
    pattern:  /reseller/account/status/edit/{slug}.{_format}
    defaults: { _controller: VanessaAgencyBundle:Reseller:accountStatusEdit , _format: html}        
    requirements:
        _method: GET|POST
        _format: html 
        
vanessa_agency_reseller_list_download_excel:
    pattern:  /reseller/download/excel/list.{_format}
    defaults: { _controller: VanessaAgencyBundle:Reseller:downloadExcel , _format: html}        
    requirements:
        _method: GET 
        _format: html 
        
                